ServerEvents.recipes(event => {
    event.remove({ output: 'mekanism:basic_control_circuit' })
    event.remove({ output: 'mekanism:advanced_control_circuit' })
    event.remove({ output: 'mekanism:elite_control_circuit' })
    event.remove({ output: 'mekanism:ultimate_control_circuit' })
    event.recipes.gtceu.forming_press('mekanism:circuits/basic')
        .itemInputs('#forge:circuits/mv', '2x minecraft:redstone')
        .itemOutputs('mekanism:basic_control_circuit')
        .EUt(120)
        .duration(300)
    event.recipes.gtceu.forming_press('mekanism:circuits/advanced')
        .itemInputs('#forge:circuits/hv', '2x mekanism:alloy_infused')
        .itemOutputs('mekanism:advanced_control_circuit')
        .EUt(120)
        .duration(300)
    event.recipes.gtceu.forming_press('mekanism:circuits/elite')
        .itemInputs('#forge:circuits/ev', '2x mekanism:alloy_reinforced')
        .itemOutputs('mekanism:elite_control_circuit')
        .EUt(120)
        .duration(300)
    event.recipes.gtceu.forming_press('mekanism:circuits/ultimate')
        .itemInputs('#forge:circuits/iv', '2x mekanism:alloy_atomic')
        .itemOutputs('mekanism:ultimate_control_circuit')
        .EUt(120)
        .duration(300)
})
